language: csharp
solution: CnpSdkForNet.sln
notifications:
  email:
    - sdksupport@vantiv.com
dotnet: 2.1
install:
  - nuget restore CnpSdkForNet/CnpSdkForNet.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release solution-name.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./MyProject.Tests/bin/Release/MyProject.Tests.dll
after_success:
 - bash <(curl -s https://codecov.io/bash)
  
